### ISSUE TITLE
UnboundLocalError: local variable 'version' referenced before assignment

### ISSUE THREAD

**Issue by woqer** [garnaat/kappa#103]
Still figuring out the root cause of this. When issuing `kappa deploy` I get the following error:

```
Traceback (most recent call last):
  File "/Users/foo/.pyenv/versions/2.7.11/envs/ansible2.1/lib/python2.7/site-packages/kappa/function.py", line 434, in update
    'For the {} stage'.format(self._context.environment))
  File "/Users/foo/.pyenv/versions/2.7.11/envs/ansible2.1/lib/python2.7/site-packages/kappa/function.py", line 333, in update_alias
    version = self.find_latest_version()
  File "/Users/foo/.pyenv/versions/2.7.11/envs/ansible2.1/lib/python2.7/site-packages/kappa/function.py", line 312, in find_latest_version
    return version
UnboundLocalError: local variable 'version' referenced before assignment
```

Though the code gets uploaded to lambda

**Comment by woqer** [comment]
Still need to debug this more. I noticed that it has something to do with the zipfile, since it also prints: `-> unable to update zip file`. But the code is actually updated in AWS... Also a second try seems to work, so my first guess is a problem on the zipfile creation code

**Comment by wvidana** [comment]
Seems related to `list_versions` not handling boto3 markers, so when a list is greater than 50, the code is unable to find the last version. Already working on a PR

**Comment by wvidana** [comment]
Fix here https://github.com/garnaat/kappa/pull/106
