### ISSUE TITLE
Error Running Current Pip Version

### ISSUE THREAD

**Issue by galvanist** [garnaat/kappa#19]
Hello,

When I try and run any kappa command after installing via pip (v0.3.0), I get the following error:

```
$ kappa config.yml status
Traceback (most recent call last):
  File "/Users/me/venv_aws/bin/kappa", line 155, in <module>
    cli(obj={})
  File "/Users/me/venv_aws/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/me/venv_aws/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/me/venv_aws/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/me/venv_aws/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/me/venv_aws/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/me/venv_aws/bin/kappa", line 97, in status
    context = Context(ctx.obj['config'], ctx.obj['debug'])
  File "/Users/me/venv_aws/lib/python2.7/site-packages/kappa/context.py", line 39, in __init__
    self, self.config['iam']['policy'])
  File "/Users/me/venv_aws/lib/python2.7/site-packages/kappa/policy.py", line 26, in __init__
    aws = kappa.aws.get_aws(context)
  File "/Users/me/venv_aws/lib/python2.7/site-packages/kappa/aws.py", line 37, in get_aws
    __Singleton_AWS = __AWS(context.profile, context.region)
  File "/Users/me/venv_aws/lib/python2.7/site-packages/kappa/aws.py", line 22, in __init__
    region_name=region_name, profile_name=profile_name)
  File "/Users/me/venv_aws/lib/python2.7/site-packages/boto3/session.py", line 76, in __init__
    self._setup_loader()
  File "/Users/me/venv_aws/lib/python2.7/site-packages/boto3/session.py", line 96, in _setup_loader
    [self._loader.data_path,
AttributeError: 'Loader' object has no attribute 'data_path'
```

If I upgrade boto3 to 0.0.18 or higher (from 0.0.16 as is installed by setup.py) with pip (I notice 0.0.21 is out now), most features seem to work.

**Comment by cyberjso** [comment]
Hello, 

I'm also having the same issue.

**Comment by garnaat** [comment]
Ok, I'll take a look.  Sorry I didn't see this earlier.

**Comment by garnaat** [comment]
This commit https://github.com/garnaat/kappa/commit/7af3b444c01fd9f9a60eb2f92f1a80b4499ed026 updates the boto3 requirement to the latest released version.  This works for me.

**Comment by garnaat** [comment]
Try the newest version when you get a chance.

**Comment by cyberjso** [comment]
Yes, It worked for me. 

Thanks!
