### ISSUE TITLE
KeyError: 'lastEventTimestamp'

### ISSUE THREAD

**Issue by Miserlou** [garnaat/kappa#23]
Happened while tailing..

    tailing logs...
    Traceback (most recent call last):
      File "/Projects/lambdas/python/env/bin/kappa", line 155, in <module>
        cli(obj={})
      File "/Projects/lambdas/python/env/lib/python2.7/site-packages/click/core.py", line 664, in __call__
        return self.main(*args, **kwargs)
      File "/Projects/lambdas/python/env/lib/python2.7/site-packages/click/core.py", line 644, in main
        rv = self.invoke(ctx)
      File "/Projects/lambdas/python/env/lib/python2.7/site-packages/click/core.py", line 991, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/Projects/lambdas/python/env/lib/python2.7/site-packages/click/core.py", line 837, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/Projects/lambdas/python/env/lib/python2.7/site-packages/click/core.py", line 464, in invoke
        return callback(*args, **kwargs)
      File "/Projects/lambdas/python/env/bin/kappa", line 89, in tail
        for e in context.tail()[-10:]:
      File "/Projects/lambdas/python/env/lib/python2.7/site-packages/kappa/context.py", line 150, in tail
        return self.function.tail()
      File "/Projects/lambdas/python/env/lib/python2.7/site-packages/kappa/function.py", line 97, in tail
        return self.log.tail()
      File "/Projects/lambdas/python/env/lib/python2.7/site-packages/kappa/log.py", line 57, in tail
        elif stream['lastEventTimestamp'] > latest_stream['lastEventTimestamp']:
    KeyError: 'lastEventTimestamp'

Normally works fine, not sure why it happened those few times. Cleared up shortly with no other changes. Just thought you should be aware.

**Comment by Miserlou** [comment]
This was happening to me enough that I just went ahead and fixed it for my own usage. Merge if it suits you, comments welcome.
