### ISSUE TITLE
Cannot create Event Sources

### ISSUE THREAD

**Issue by gamename** [garnaat/kappa#45]
Hi,

I love kappa and just started using it.  Its very well written.

But, for some reason I cannot get "Event Sources" to connect. Here is the error:
```
$ kappa ./config.yml add_event_sources 
adding event sources...
        Unable to add S3 event source
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kappa/event_source.py", line 142, in add
    NotificationConfiguration=notification_spec)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 258, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 312, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidArgument) when calling the PutBucketNotification operation: Unable to validate the following destination configurations
...done
```

Here is my config file:
```
---
# Change the profile and region to suit your application
region: us-east-1
iam:
  # In this case, we are using an existing managed policy so we just
  # need to put the name of that policy here.
  policy:
    name: AWSLambdaExecute
  # The name of the IAM role used for executing the Lambda function.
  # The policy listed above will be attached to this role once it is created.
  role:
    name: tennis-lambda-s3-execution-role
lambda:
  name: cronitor_handler
  zipfile_name: cronitor_handler.zip
  description: Monitor s3 updates for Cronitor
  path:  cronitor_handler.py
  handler: lambda_function.cronitor_handler
  runtime: python2.7
  memory_size: 128
  timeout: 10
  mode: event
  test_data: event.json
  event_sources:
    - arn: arn:aws:s3:::test-ngd-db-backups
      events:
        - s3:ObjectCreated:*
```

Any ideas what I may be doing wrong?

Thanks
-T

**Comment by garnaat** [comment]
Sorry for the slow response.  I have just merged a lot of changes into the develop branch.  I'll start taking a look at this issue.

**Comment by Miserlou** [comment]
I've started getting this error all of a sudden. I don't know why or what changed. Very annoying!

**Comment by Miserlou** [comment]
Did you ever figure this one out @gamename ?

**Comment by josegonzalez** [comment]
@Miserlou are you using the latest release? Or perhaps did you upgrade something?

**Comment by Miserlou** [comment]
Figured this out, related: http://docs.aws.amazon.com/lambda/latest/dg/with-s3-example-configure-event-source.html

Not sure why Kappa didn't handle it though.
