### ISSUE TITLE
Error: pkg_resources._vendor.packaging.requirements.InvalidRequirement

### ISSUE THREAD

**Issue by RAbraham** [garnaat/kappa#51]
Hi,
I installed the latest development branch with 
```
pip install git+https://github.com/garnaat/kappa.git
```
and then when I run kappa, I get an error:
```
console> kappa
Traceback (most recent call last):
  File "/Users/rabraham/Documents/dev/python/virtual_envs/tracker_env/bin/kappa", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/rabraham/Documents/dev/python/virtual_envs/tracker_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2912, in <module>
    @_call_aside
  File "/Users/rabraham/Documents/dev/python/virtual_envs/tracker_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2898, in _call_aside
    f(*args, **kwargs)
  File "/Users/rabraham/Documents/dev/python/virtual_envs/tracker_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/rabraham/Documents/dev/python/virtual_envs/tracker_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 642, in _build_master
    ws.require(__requires__)
  File "/Users/rabraham/Documents/dev/python/virtual_envs/tracker_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/rabraham/Documents/dev/python/virtual_envs/tracker_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 838, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/Users/rabraham/Documents/dev/python/virtual_envs/tracker_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2462, in requires
    dm = self._dep_map
  File "/Users/rabraham/Documents/dev/python/virtual_envs/tracker_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2686, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Users/rabraham/Documents/dev/python/virtual_envs/tracker_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2696, in _compute_dependencies
    current_req = packaging.requirements.Requirement(req)
  File "/Users/rabraham/Documents/dev/python/virtual_envs/tracker_env/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'and plat'"
```

When I install `kappa` with `pip install kappa` it works but I am trying to get the latest version which reflects the Github docs.

**Comment by josegonzalez** [comment]
Development should work fine now, I've just tested this out in a local development setup:

```
[kappa] jose@mactaku:~/src/opensource/kappa git:master $ pip install git+https://github.com/garnaat/kappa.git
Collecting git+https://github.com/garnaat/kappa.git
  Cloning https://github.com/garnaat/kappa.git to /var/folders/fb/tdb_c9rj1v9982l6qrd4whrw0000gn/T/pip-y3I0E1-build
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.11 in /Users/jose/.virtualenvs/kappa/lib/python2.7/site-packages (from kappa==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): boto3>=1.2.3 in /Users/jose/.virtualenvs/kappa/lib/python2.7/site-packages (from kappa==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): click>=5.1 in /Users/jose/.virtualenvs/kappa/lib/python2.7/site-packages (from kappa==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): placebo>=0.8.1 in /Users/jose/.virtualenvs/kappa/lib/python2.7/site-packages (from kappa==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): jmespath<1.0.0,>=0.7.1 in /Users/jose/.virtualenvs/kappa/lib/python2.7/site-packages (from boto3>=1.2.3->kappa==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /Users/jose/.virtualenvs/kappa/lib/python2.7/site-packages (from boto3>=1.2.3->kappa==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): botocore<1.5.0,>=1.4.1 in /Users/jose/.virtualenvs/kappa/lib/python2.7/site-packages (from boto3>=1.2.3->kappa==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.10 in /Users/jose/.virtualenvs/kappa/lib/python2.7/site-packages (from botocore<1.5.0,>=1.4.1->boto3>=1.2.3->kappa==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil<3.0.0,>=2.1 in /Users/jose/.virtualenvs/kappa/lib/python2.7/site-packages (from botocore<1.5.0,>=1.4.1->boto3>=1.2.3->kappa==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /Users/jose/.virtualenvs/kappa/lib/python2.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.5.0,>=1.4.1->boto3>=1.2.3->kappa==0.5.1)
Installing collected packages: kappa
  Running setup.py install for kappa ... done
Successfully installed kappa-0.5.1
[kappa] jose@mactaku:~/src/opensource/kappa git:master $ kappa
Usage: kappa [OPTIONS] COMMAND [ARGS]...

Options:
  --config FILENAME        Name of config file (default is kappa.yml)
  --debug / --no-debug     Turn on debugging output
  --env TEXT               Specify which environment to work with (default
                           dev)
  --record-path DIRECTORY  Uses placebo to record AWS responses to this path
  --help                   Show this message and exit.

Commands:
  delete         Delete the Lambda function and related...
  deploy         Deploy the Lambda function and any policies...
  event_sources  List, enable, and disable event sources...
  invoke         Invoke the command synchronously
  status         Print a status of this Lambda function
  tail           Show the last 10 lines of the log file
  test           Test the command synchronously
```
