### ISSUE TITLE
starting troubles 

### ISSUE THREAD

**Issue by viswaug** [garnaat/kappa#56]
First off, i wanted to mention how awesome this project idea is and thank you for implementing it. I am just starting off with trying kappa and ran into the following issue when trying to run kappa for the first time. The readme seems to be out of date with the current commandline options. The commandline help doesn't really say what it expects for the "config" placeholder. I tried passing in the file name "kappa.yml" for the config option and ended up with the following error. Any thoughts/suggestions on what could be going wrong here?

(lambdaStats) osboxes@osboxes:~/projects/lambdaStats2> kappa --debug kappa.yml status
Traceback (most recent call last):
  File "/home/osboxes/envs/lambdaStats/bin/kappa", line 155, in <module>
    cli(obj={})
  File "/home/osboxes/envs/lambdaStats/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/osboxes/envs/lambdaStats/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/osboxes/envs/lambdaStats/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/osboxes/envs/lambdaStats/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/osboxes/envs/lambdaStats/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/osboxes/envs/lambdaStats/bin/kappa", line 98, in status
    status = context.status()
  File "/home/osboxes/envs/lambdaStats/local/lib/python2.7/site-packages/kappa/context.py", line 173, in status
    status['function'] = self.function.status()
  File "/home/osboxes/envs/lambdaStats/local/lib/python2.7/site-packages/kappa/function.py", line 192, in status
    LOG.debug('getting status for function %s', self.name)
  File "/home/osboxes/envs/lambdaStats/local/lib/python2.7/site-packages/kappa/function.py", line 38, in name
    return self._config['name']
KeyError: 'name'

**Comment by guydaher** [comment]
Did you install the latest stable version or the development version? Because in my case, a few days ago, I started off with the stable version, and tried following the ReadMe, but I was always getting errors. When I switched to the development version, then commands would work. The ReadMe is tailored towards the development version only it seems.

**Comment by viswaug** [comment]
@guydaher that was it. the development version works as advertised. I glanced at the version number in the _version file and assumed they were they same... assumptions always get you in trouble :) Thank you. Appreciate it

**Comment by guydaher** [comment]
Haha yes indeed. Glad I could help!

**Comment by josegonzalez** [comment]
I've made a new release so the docs should match the latest release!
